\doxysection{Exception Handling}
\hypertarget{_exception_handling}{}\label{_exception_handling}\index{Exception Handling@{Exception Handling}}
This chapters discusses how to handle exceptions from a submitted taskflow so you can properly catch or propagate exceptions in your workload.\hypertarget{_exception_handling_CatchAnExceptionFromARunningTaskflow}{}\doxysubsection{\texorpdfstring{Catch an Exception from a Running Taskflow}{Catch an Exception from a Running Taskflow}}\label{_exception_handling_CatchAnExceptionFromARunningTaskflow}
When a task throws an exception, the executor will store that exception in the shared state referenced by the \doxylink{classtf_1_1_future}{tf\+::\+Future} handle. You can catch that exception via calling the {\ttfamily get} method\+:


\begin{DoxyCode}{0}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_executor}{tf::Executor}}\ \mbox{\hyperlink{thread__pool_8cpp_a543e564a8407bbeac15cb2d929fec755}{executor}};}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_taskflow}{tf::Taskflow}}\ \mbox{\hyperlink{poisson_8hpp_aa56fe360bb0ae38e0082f49e394ff825}{taskflow}};}
\DoxyCodeLine{}
\DoxyCodeLine{\mbox{\hyperlink{poisson_8hpp_aa56fe360bb0ae38e0082f49e394ff825}{taskflow}}.emplace([]()\{\ \textcolor{keywordflow}{throw}\ std::runtime\_error(\textcolor{stringliteral}{"{}exception"{}});\ \});}
\DoxyCodeLine{}
\DoxyCodeLine{\textcolor{keywordflow}{try}\ \{}
\DoxyCodeLine{\ \ \mbox{\hyperlink{thread__pool_8cpp_a543e564a8407bbeac15cb2d929fec755}{executor}}.run(\mbox{\hyperlink{poisson_8hpp_aa56fe360bb0ae38e0082f49e394ff825}{taskflow}}).get();}
\DoxyCodeLine{\}}
\DoxyCodeLine{\textcolor{keywordflow}{catch}(\textcolor{keyword}{const}\ std::runtime\_error\&\ \mbox{\hyperlink{_cwise__array__power__array_8cpp_a9cb86ff854760bf91a154f2724a9101d}{e}})\ \{}
\DoxyCodeLine{\ \ std::cerr\ <<\ \mbox{\hyperlink{_cwise__array__power__array_8cpp_a9cb86ff854760bf91a154f2724a9101d}{e}}.what()\ <<\ std::endl;}
\DoxyCodeLine{\}}

\end{DoxyCode}


\begin{DoxyAttention}{注意}
As \doxylink{classtf_1_1_future}{tf\+::\+Future} is derived from @std\+\_\+future, it inherits all the exception handling behaviors defined by the C++ standard.
\end{DoxyAttention}
An exception will automatically cancel the execution of its parent taskflow. All the subsequent tasks that have dependencies on that exception task will not run. For instance, the following code defines two tasks, {\ttfamily \doxylink{bench__gemm_8cpp_addc86e8508f14411ec98f521c520f875}{A}} and {\ttfamily \doxylink{bench__gemm_8cpp_a37a83060ac796961b44991c836f083f7}{B}}, where {\ttfamily \doxylink{bench__gemm_8cpp_a37a83060ac796961b44991c836f083f7}{B}} runs after {\ttfamily \doxylink{bench__gemm_8cpp_addc86e8508f14411ec98f521c520f875}{A}}. When {\ttfamily \doxylink{bench__gemm_8cpp_addc86e8508f14411ec98f521c520f875}{A}} throws an exception, the executor will cancel the execution of the taskflow, stopping every tasks that run after {\ttfamily \doxylink{bench__gemm_8cpp_addc86e8508f14411ec98f521c520f875}{A}}. In this case, {\ttfamily \doxylink{bench__gemm_8cpp_a37a83060ac796961b44991c836f083f7}{B}} will not run.


\begin{DoxyCode}{0}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_executor}{tf::Executor}}\ \mbox{\hyperlink{thread__pool_8cpp_a543e564a8407bbeac15cb2d929fec755}{executor}};}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_taskflow}{tf::Taskflow}}\ \mbox{\hyperlink{poisson_8hpp_aa56fe360bb0ae38e0082f49e394ff825}{taskflow}};}
\DoxyCodeLine{}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_task}{tf::Task}}\ \mbox{\hyperlink{bench__gemm_8cpp_addc86e8508f14411ec98f521c520f875}{A}}\ =\ \mbox{\hyperlink{poisson_8hpp_aa56fe360bb0ae38e0082f49e394ff825}{taskflow}}.emplace([]()\{\ \textcolor{keywordflow}{throw}\ std::runtime\_error(\textcolor{stringliteral}{"{}exception\ on\ A"{}});\ \});}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_task}{tf::Task}}\ \mbox{\hyperlink{bench__gemm_8cpp_a37a83060ac796961b44991c836f083f7}{B}}\ =\ \mbox{\hyperlink{poisson_8hpp_aa56fe360bb0ae38e0082f49e394ff825}{taskflow}}.emplace([]()\{\ std::cout\ <<\ \textcolor{stringliteral}{"{}Task\ B\(\backslash\)n"{}};\ \});}
\DoxyCodeLine{\mbox{\hyperlink{bench__gemm_8cpp_addc86e8508f14411ec98f521c520f875}{A}}.precede(\mbox{\hyperlink{bench__gemm_8cpp_a37a83060ac796961b44991c836f083f7}{B}});}
\DoxyCodeLine{}
\DoxyCodeLine{\textcolor{keywordflow}{try}\ \{}
\DoxyCodeLine{\ \ \mbox{\hyperlink{thread__pool_8cpp_a543e564a8407bbeac15cb2d929fec755}{executor}}.\mbox{\hyperlink{classtf_1_1_executor_a519777f5783981d534e9e53b99712069}{run}}(\mbox{\hyperlink{poisson_8hpp_aa56fe360bb0ae38e0082f49e394ff825}{taskflow}}).get();}
\DoxyCodeLine{\}}
\DoxyCodeLine{\textcolor{keywordflow}{catch}(\textcolor{keyword}{const}\ std::runtime\_error\&\ \mbox{\hyperlink{_cwise__array__power__array_8cpp_a9cb86ff854760bf91a154f2724a9101d}{e}})\ \{}
\DoxyCodeLine{\ \ std::cerr\ <<\ \mbox{\hyperlink{_cwise__array__power__array_8cpp_a9cb86ff854760bf91a154f2724a9101d}{e}}.what()\ <<\ std::endl;}
\DoxyCodeLine{\}}

\end{DoxyCode}



\begin{DoxyCode}{0}
\DoxyCodeLine{\{.shell-\/session\}\ }
\DoxyCodeLine{\string~\$\ exception\ on\ \mbox{\hyperlink{bench__gemm_8cpp_addc86e8508f14411ec98f521c520f875}{A}}}
\DoxyCodeLine{\textcolor{preprocessor}{\#\ execution\ of\ taskflow\ is\ cancelled\ after\ an\ execution\ is\ thrown}}

\end{DoxyCode}


When multiple tasks throw exceptions simultaneously, the executor will only catch one exception and store it in the shared state. Other exceptions will be silently ignored. For example, the following taskflow may concurrently throw two exceptions from task {\ttfamily \doxylink{bench__gemm_8cpp_a37a83060ac796961b44991c836f083f7}{B}} and task {\ttfamily C}. Only one exception, either {\ttfamily \doxylink{bench__gemm_8cpp_a37a83060ac796961b44991c836f083f7}{B}} or {\ttfamily C}, will be propagated.


\begin{DoxyCode}{0}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_executor}{tf::Executor}}\ \mbox{\hyperlink{thread__pool_8cpp_a543e564a8407bbeac15cb2d929fec755}{executor}};}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_taskflow}{tf::Taskflow}}\ \mbox{\hyperlink{poisson_8hpp_aa56fe360bb0ae38e0082f49e394ff825}{taskflow}};}
\DoxyCodeLine{}
\DoxyCodeLine{\textcolor{keyword}{auto}\ [\mbox{\hyperlink{bench__gemm_8cpp_addc86e8508f14411ec98f521c520f875}{A}},\ \mbox{\hyperlink{bench__gemm_8cpp_a37a83060ac796961b44991c836f083f7}{B}},\ \mbox{\hyperlink{test__buffer__node_8cpp_ac4cf4b2ab929bd23951a8676eeac086b}{C}},\ \mbox{\hyperlink{_eigen_solver___eigen_solver___matrix_type_8cpp_a925331f9b6e4844293d36a8df2256d38}{D}}]\ =\ \mbox{\hyperlink{poisson_8hpp_aa56fe360bb0ae38e0082f49e394ff825}{taskflow}}.emplace(}
\DoxyCodeLine{\ \ []()\ \{\ std::cout\ <<\ \textcolor{stringliteral}{"{}TaskA\(\backslash\)n"{}};\ \},}
\DoxyCodeLine{\ \ []()\ \{\ }
\DoxyCodeLine{\ \ \ \ std::cout\ <<\ \textcolor{stringliteral}{"{}TaskB\(\backslash\)n"{}};}
\DoxyCodeLine{\ \ \ \ \textcolor{keywordflow}{throw}\ std::runtime\_error(\textcolor{stringliteral}{"{}Exception\ on\ Task\ B"{}});}
\DoxyCodeLine{\ \ \},}
\DoxyCodeLine{\ \ []()\ \{\ }
\DoxyCodeLine{\ \ \ \ std::cout\ <<\ \textcolor{stringliteral}{"{}TaskC\(\backslash\)n"{}};\ }
\DoxyCodeLine{\ \ \ \ \textcolor{keywordflow}{throw}\ std::runtime\_error(\textcolor{stringliteral}{"{}Exception\ on\ Task\ C"{}});}
\DoxyCodeLine{\ \ \},}
\DoxyCodeLine{\ \ []()\ \{\ std::cout\ <<\ \textcolor{stringliteral}{"{}TaskD\ will\ not\ be\ printed\ due\ to\ exception\(\backslash\)n"{}};\ \}}
\DoxyCodeLine{);}
\DoxyCodeLine{}
\DoxyCodeLine{\mbox{\hyperlink{bench__gemm_8cpp_addc86e8508f14411ec98f521c520f875}{A}}.precede(\mbox{\hyperlink{bench__gemm_8cpp_a37a83060ac796961b44991c836f083f7}{B}},\ \mbox{\hyperlink{test__buffer__node_8cpp_ac4cf4b2ab929bd23951a8676eeac086b}{C}});\ \ \textcolor{comment}{//\ A\ runs\ before\ B\ and\ C}}
\DoxyCodeLine{\mbox{\hyperlink{_eigen_solver___eigen_solver___matrix_type_8cpp_a925331f9b6e4844293d36a8df2256d38}{D}}.succeed(\mbox{\hyperlink{bench__gemm_8cpp_a37a83060ac796961b44991c836f083f7}{B}},\ \mbox{\hyperlink{test__buffer__node_8cpp_ac4cf4b2ab929bd23951a8676eeac086b}{C}});\ \ \textcolor{comment}{//\ D\ runs\ after\ \ B\ and\ C}}
\DoxyCodeLine{}
\DoxyCodeLine{\textcolor{keywordflow}{try}\ \{}
\DoxyCodeLine{\ \ \mbox{\hyperlink{thread__pool_8cpp_a543e564a8407bbeac15cb2d929fec755}{executor}}.\mbox{\hyperlink{classtf_1_1_executor_a519777f5783981d534e9e53b99712069}{run}}(\mbox{\hyperlink{poisson_8hpp_aa56fe360bb0ae38e0082f49e394ff825}{taskflow}}).get();}
\DoxyCodeLine{\}}
\DoxyCodeLine{\textcolor{keywordflow}{catch}(\textcolor{keyword}{const}\ std::runtime\_error\&\ \mbox{\hyperlink{_cwise__array__power__array_8cpp_a9cb86ff854760bf91a154f2724a9101d}{e}})\ \{}
\DoxyCodeLine{\ \ \textcolor{comment}{//\ caught\ either\ B's\ or\ C's\ exception}}
\DoxyCodeLine{\ \ std::cout\ <<\ \mbox{\hyperlink{_cwise__array__power__array_8cpp_a9cb86ff854760bf91a154f2724a9101d}{e}}.what()\ <<\ std::endl;}
\DoxyCodeLine{\}}

\end{DoxyCode}
\hypertarget{_exception_handling_CatchAnExceptionFromASubflow}{}\doxysubsection{\texorpdfstring{Catch an Exception from a Subflow}{Catch an Exception from a Subflow}}\label{_exception_handling_CatchAnExceptionFromASubflow}
When you join a subflow using \doxylink{classtf_1_1_subflow_a59fcac1323e70d920088dd37bd0be245}{tf\+::\+Subflow\+::join}, you can catch an exception thrown by its children tasks. For example, the following code catches an exception from the child task {\ttfamily \doxylink{bench__gemm_8cpp_addc86e8508f14411ec98f521c520f875}{A}} of the subflow {\ttfamily sf}\+:


\begin{DoxyCode}{0}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_executor}{tf::Executor}}\ \mbox{\hyperlink{thread__pool_8cpp_a543e564a8407bbeac15cb2d929fec755}{executor}};}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_taskflow}{tf::Taskflow}}\ \mbox{\hyperlink{poisson_8hpp_aa56fe360bb0ae38e0082f49e394ff825}{taskflow}};}
\DoxyCodeLine{}
\DoxyCodeLine{\mbox{\hyperlink{poisson_8hpp_aa56fe360bb0ae38e0082f49e394ff825}{taskflow}}.emplace([](\mbox{\hyperlink{classtf_1_1_subflow}{tf::Subflow}}\&\ sf)\ \{}
\DoxyCodeLine{\ \ \mbox{\hyperlink{classtf_1_1_task}{tf::Task}}\ \mbox{\hyperlink{bench__gemm_8cpp_addc86e8508f14411ec98f521c520f875}{A}}\ =\ sf.emplace([]()\ \{\ }
\DoxyCodeLine{\ \ \ \ std::cout\ <<\ \textcolor{stringliteral}{"{}Task\ A\(\backslash\)n"{}};}
\DoxyCodeLine{\ \ \ \ \textcolor{keywordflow}{throw}\ std::runtime\_error(\textcolor{stringliteral}{"{}exception\ on\ A"{}});\ }
\DoxyCodeLine{\ \ \});}
\DoxyCodeLine{\ \ \mbox{\hyperlink{classtf_1_1_task}{tf::Task}}\ \mbox{\hyperlink{bench__gemm_8cpp_a37a83060ac796961b44991c836f083f7}{B}}\ =\ sf.emplace([]()\ \{\ }
\DoxyCodeLine{\ \ \ \ std::cout\ <<\ \textcolor{stringliteral}{"{}Task\ B\(\backslash\)n"{}};\ }
\DoxyCodeLine{\ \ \});}
\DoxyCodeLine{\ \ \mbox{\hyperlink{bench__gemm_8cpp_addc86e8508f14411ec98f521c520f875}{A}}.precede(\mbox{\hyperlink{bench__gemm_8cpp_a37a83060ac796961b44991c836f083f7}{B}});}
\DoxyCodeLine{\ \ }
\DoxyCodeLine{\ \ \textcolor{comment}{//\ catch\ the\ exception}}
\DoxyCodeLine{\ \ \textcolor{keywordflow}{try}\ \{}
\DoxyCodeLine{\ \ \ \ sf.\mbox{\hyperlink{classtf_1_1_subflow_a59fcac1323e70d920088dd37bd0be245}{join}}();}
\DoxyCodeLine{\ \ \}}
\DoxyCodeLine{\ \ \textcolor{keywordflow}{catch}(\textcolor{keyword}{const}\ std::runtime\_error\&\ re)\ \{}
\DoxyCodeLine{\ \ \ \ std::cout\ <<\ \textcolor{stringliteral}{"{}exception\ thrown\ during\ subflow\ joining:\ "{}}\ <<\ \mbox{\hyperlink{namespacectre_a1eb09093367d4fb6ecf857afc771533a}{re}}.what()\ <<\ \textcolor{charliteral}{'\(\backslash\)n'};}
\DoxyCodeLine{\ \ \}}
\DoxyCodeLine{\});}
\DoxyCodeLine{}
\DoxyCodeLine{\mbox{\hyperlink{thread__pool_8cpp_a543e564a8407bbeac15cb2d929fec755}{executor}}.\mbox{\hyperlink{classtf_1_1_executor_a519777f5783981d534e9e53b99712069}{run}}(\mbox{\hyperlink{poisson_8hpp_aa56fe360bb0ae38e0082f49e394ff825}{taskflow}}).get();}

\end{DoxyCode}


When an exception is thrown, it will cancel the execution of the parent subflow. All the subsequent tasks that depend on that exception task will not run. The above code example has the following output\+:


\begin{DoxyCode}{0}
\DoxyCodeLine{\{.shell-\/session\}\ }
\DoxyCodeLine{Task\ \mbox{\hyperlink{bench__gemm_8cpp_addc86e8508f14411ec98f521c520f875}{A}}}
\DoxyCodeLine{exception\ thrown\ during\ subflow\ joining:\ exception\ on\ \mbox{\hyperlink{bench__gemm_8cpp_addc86e8508f14411ec98f521c520f875}{A}}}

\end{DoxyCode}


Uncaught exception will be propagated to the parent level until being explicitly caught. For example, the code below will propagate the exception to the parent of the subflow, which in this case in its taskflow.


\begin{DoxyCode}{0}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_executor}{tf::Executor}}\ \mbox{\hyperlink{thread__pool_8cpp_a543e564a8407bbeac15cb2d929fec755}{executor}};}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_taskflow}{tf::Taskflow}}\ \mbox{\hyperlink{poisson_8hpp_aa56fe360bb0ae38e0082f49e394ff825}{taskflow}};}
\DoxyCodeLine{}
\DoxyCodeLine{\mbox{\hyperlink{poisson_8hpp_aa56fe360bb0ae38e0082f49e394ff825}{taskflow}}.emplace([](\mbox{\hyperlink{classtf_1_1_subflow}{tf::Subflow}}\&\ sf)\ \{}
\DoxyCodeLine{\ \ \mbox{\hyperlink{classtf_1_1_task}{tf::Task}}\ \mbox{\hyperlink{bench__gemm_8cpp_addc86e8508f14411ec98f521c520f875}{A}}\ =\ sf.emplace([]()\ \{}
\DoxyCodeLine{\ \ \ \ std::cout\ <<\ \textcolor{stringliteral}{"{}Task\ A\(\backslash\)n"{}};}
\DoxyCodeLine{\ \ \ \ \textcolor{keywordflow}{throw}\ std::runtime\_error(\textcolor{stringliteral}{"{}exception\ on\ A"{}});}
\DoxyCodeLine{\ \ \});}
\DoxyCodeLine{\ \ \mbox{\hyperlink{classtf_1_1_task}{tf::Task}}\ \mbox{\hyperlink{bench__gemm_8cpp_a37a83060ac796961b44991c836f083f7}{B}}\ =\ sf.emplace([]()\ \{}
\DoxyCodeLine{\ \ \ \ std::cout\ <<\ \textcolor{stringliteral}{"{}Task\ B\(\backslash\)n"{}};\ }
\DoxyCodeLine{\ \ \});\ }
\DoxyCodeLine{\ \ \mbox{\hyperlink{bench__gemm_8cpp_addc86e8508f14411ec98f521c520f875}{A}}.precede(\mbox{\hyperlink{bench__gemm_8cpp_a37a83060ac796961b44991c836f083f7}{B}});}
\DoxyCodeLine{}
\DoxyCodeLine{\ \ \textcolor{comment}{//\ uncaught\ exception\ will\ propagate\ to\ the\ parent}}
\DoxyCodeLine{\ \ sf.\mbox{\hyperlink{classtf_1_1_subflow_a59fcac1323e70d920088dd37bd0be245}{join}}();}
\DoxyCodeLine{\});}
\DoxyCodeLine{}
\DoxyCodeLine{\textcolor{keywordflow}{try}}
\DoxyCodeLine{\{}
\DoxyCodeLine{\ \ \mbox{\hyperlink{thread__pool_8cpp_a543e564a8407bbeac15cb2d929fec755}{executor}}.\mbox{\hyperlink{classtf_1_1_executor_a519777f5783981d534e9e53b99712069}{run}}(\mbox{\hyperlink{poisson_8hpp_aa56fe360bb0ae38e0082f49e394ff825}{taskflow}}).get();}
\DoxyCodeLine{\}}
\DoxyCodeLine{\textcolor{keywordflow}{catch}\ (\textcolor{keyword}{const}\ std::runtime\_error\&\ re)}
\DoxyCodeLine{\{}
\DoxyCodeLine{\ \ std::cout\ <<\ \textcolor{stringliteral}{"{}exception\ thrown\ from\ running\ the\ taskflow:\ "{}}\ <<\ \mbox{\hyperlink{namespacectre_a1eb09093367d4fb6ecf857afc771533a}{re}}.what()\ <<\ \textcolor{charliteral}{'\(\backslash\)n'};}
\DoxyCodeLine{\}}

\end{DoxyCode}



\begin{DoxyCode}{0}
\DoxyCodeLine{\{.shell-\/session\}\ }
\DoxyCodeLine{Task\ \mbox{\hyperlink{bench__gemm_8cpp_addc86e8508f14411ec98f521c520f875}{A}}}
\DoxyCodeLine{exception\ thrown\ from\ \mbox{\hyperlink{empty_8c_af1f449cc09f8d36befcce07bc38c29c0}{running}}\ the\ \mbox{\hyperlink{poisson_8hpp_aa56fe360bb0ae38e0082f49e394ff825}{taskflow}}:\ exception\ on\ \mbox{\hyperlink{bench__gemm_8cpp_addc86e8508f14411ec98f521c520f875}{A}}}

\end{DoxyCode}
\hypertarget{_exception_handling_CatchAnExceptionFromAnAsyncTask}{}\doxysubsection{\texorpdfstring{Catch an Exception from an Async Task}{Catch an Exception from an Async Task}}\label{_exception_handling_CatchAnExceptionFromAnAsyncTask}
Similar to @std\+\_\+future, \doxylink{classtf_1_1_executor_af960048056f7c6b5bc71f4f526f05df7}{tf\+::\+Executor\+::async} will store the exception in the shared state referenced by the returned @std\+\_\+future handle.


\begin{DoxyCode}{0}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_executor}{tf::Executor}}\ \mbox{\hyperlink{thread__pool_8cpp_a543e564a8407bbeac15cb2d929fec755}{executor}};}
\DoxyCodeLine{\textcolor{keyword}{auto}\ fu\ =\ \mbox{\hyperlink{thread__pool_8cpp_a543e564a8407bbeac15cb2d929fec755}{executor}}.async([]()\{\ \textcolor{keywordflow}{throw}\ std::runtime\_error(\textcolor{stringliteral}{"{}exception"{}});\ \});}
\DoxyCodeLine{\textcolor{keywordflow}{try}\ \{}
\DoxyCodeLine{\ \ fu.get();}
\DoxyCodeLine{\}}
\DoxyCodeLine{\textcolor{keywordflow}{catch}(\textcolor{keyword}{const}\ std::runtime\_error\&\ \mbox{\hyperlink{_cwise__array__power__array_8cpp_a9cb86ff854760bf91a154f2724a9101d}{e}})\ \{}
\DoxyCodeLine{\ \ std::cerr\ <<\ \mbox{\hyperlink{_cwise__array__power__array_8cpp_a9cb86ff854760bf91a154f2724a9101d}{e}}.what()\ <<\ std::endl;}
\DoxyCodeLine{\}}

\end{DoxyCode}


Running the program will show the exception message on the async task\+:


\begin{DoxyCode}{0}
\DoxyCodeLine{\{.shell-\/session\}\ }
\DoxyCodeLine{\string~\$\ exception}

\end{DoxyCode}


On the other hand, since \doxylink{classtf_1_1_executor_a0461cb2c459c9f9473c72af06af9c701}{tf\+::\+Executor\+::silent\+\_\+async} does not return any future handle, any exception thrown from a silent-\/async task will be silently caught by the executor and (1) propagated to the its parent task if the parent task exists or (2) ignored if the parent task does not exist.


\begin{DoxyCode}{0}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_taskflow}{tf::Taskflow}}\ \mbox{\hyperlink{poisson_8hpp_aa56fe360bb0ae38e0082f49e394ff825}{taskflow}};}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_executor}{tf::Executor}}\ \mbox{\hyperlink{thread__pool_8cpp_a543e564a8407bbeac15cb2d929fec755}{executor}};}
\DoxyCodeLine{}
\DoxyCodeLine{\textcolor{comment}{//\ exception\ will\ be\ silently\ ignored}}
\DoxyCodeLine{\mbox{\hyperlink{thread__pool_8cpp_a543e564a8407bbeac15cb2d929fec755}{executor}}.silent\_async([]()\{\ \textcolor{keywordflow}{throw}\ std::runtime\_error(\textcolor{stringliteral}{"{}exception"{}});\ \});}
\DoxyCodeLine{}
\DoxyCodeLine{\textcolor{comment}{//\ exception\ will\ be\ propagated\ to\ the\ parent\ tf::Runtime\ task\ and\ then\ its\ Taskflow}}
\DoxyCodeLine{\mbox{\hyperlink{poisson_8hpp_aa56fe360bb0ae38e0082f49e394ff825}{taskflow}}.emplace([\&](\mbox{\hyperlink{classtf_1_1_runtime}{tf::Runtime}}\&\ rt)\{}
\DoxyCodeLine{\ \ rt.\mbox{\hyperlink{classtf_1_1_runtime_a0ce29efa2106c8c5a1432e4a55ab2e05}{silent\_async}}([]()\{\ \textcolor{keywordflow}{throw}\ std::runtime\_error(\textcolor{stringliteral}{"{}exception"{}});\ \});}
\DoxyCodeLine{\});}
\DoxyCodeLine{\textcolor{keywordflow}{try}\ \{}
\DoxyCodeLine{\ \ \mbox{\hyperlink{poisson_8hpp_aa56fe360bb0ae38e0082f49e394ff825}{taskflow}}.get();}
\DoxyCodeLine{\}}
\DoxyCodeLine{\textcolor{keywordflow}{catch}(\textcolor{keyword}{const}\ std::runtime\_error\&\ re)\ \{}
\DoxyCodeLine{\ \ std::cout\ <<\ \mbox{\hyperlink{namespacectre_a1eb09093367d4fb6ecf857afc771533a}{re}}.what()\ <<\ std::endl;}
\DoxyCodeLine{\}}

\end{DoxyCode}
\hypertarget{_exception_handling_CatchAnExceptionFromACorunLoop}{}\doxysubsection{\texorpdfstring{Catch an Exception from a Corun Loop}{Catch an Exception from a Corun Loop}}\label{_exception_handling_CatchAnExceptionFromACorunLoop}
When you corun a graph via \doxylink{classtf_1_1_executor_a8fcd9e0557922bb8194999f0cd433ea8}{tf\+::\+Executor\+::corun} or \doxylink{classtf_1_1_runtime_a1c772e90614302024cfa52fa86d75cac}{tf\+::\+Runtime\+::corun}, any exception will be thrown during the execution. For example, the code below will throw an exception during the execution of {\ttfamily taskflow1}\+:


\begin{DoxyCode}{0}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_executor}{tf::Executor}}\ \mbox{\hyperlink{thread__pool_8cpp_a543e564a8407bbeac15cb2d929fec755}{executor}};}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_taskflow}{tf::Taskflow}}\ taskflow1;}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_taskflow}{tf::Taskflow}}\ taskflow2;}
\DoxyCodeLine{}
\DoxyCodeLine{taskflow1.\mbox{\hyperlink{classtf_1_1_flow_builder_a60d7a666cab71ecfa3010b2efb0d6b57}{emplace}}([]()\{}
\DoxyCodeLine{\ \ \textcolor{keywordflow}{throw}\ std::runtime\_error(\textcolor{stringliteral}{"{}exception"{}});}
\DoxyCodeLine{\});\ }
\DoxyCodeLine{taskflow2.\mbox{\hyperlink{classtf_1_1_flow_builder_a60d7a666cab71ecfa3010b2efb0d6b57}{emplace}}([\&]()\{}
\DoxyCodeLine{\ \ \textcolor{keywordflow}{try}\ \{}
\DoxyCodeLine{\ \ \ \ \mbox{\hyperlink{thread__pool_8cpp_a543e564a8407bbeac15cb2d929fec755}{executor}}.corun(taskflow1);}
\DoxyCodeLine{\ \ \}\ \textcolor{keywordflow}{catch}(\textcolor{keyword}{const}\ std::runtime\_error\&\ re)\ \{}
\DoxyCodeLine{\ \ \ \ std::cout\ <<\ \mbox{\hyperlink{namespacectre_a1eb09093367d4fb6ecf857afc771533a}{re}}.what()\ <<\ std::endl;}
\DoxyCodeLine{\ \ \}}
\DoxyCodeLine{\});\ }
\DoxyCodeLine{\mbox{\hyperlink{thread__pool_8cpp_a543e564a8407bbeac15cb2d929fec755}{executor}}.\mbox{\hyperlink{classtf_1_1_executor_a519777f5783981d534e9e53b99712069}{run}}(taskflow2).get();}

\end{DoxyCode}


We can observe the same behavior when using \doxylink{classtf_1_1_runtime_a1c772e90614302024cfa52fa86d75cac}{tf\+::\+Runtime\+::corun}\+:


\begin{DoxyCode}{0}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_executor}{tf::Executor}}\ \mbox{\hyperlink{thread__pool_8cpp_a543e564a8407bbeac15cb2d929fec755}{executor}};}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_taskflow}{tf::Taskflow}}\ taskflow1;}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_taskflow}{tf::Taskflow}}\ taskflow2;}
\DoxyCodeLine{}
\DoxyCodeLine{taskflow1.\mbox{\hyperlink{classtf_1_1_flow_builder_a60d7a666cab71ecfa3010b2efb0d6b57}{emplace}}([]()\{}
\DoxyCodeLine{\ \ \textcolor{keywordflow}{throw}\ std::runtime\_error(\textcolor{stringliteral}{"{}exception"{}});}
\DoxyCodeLine{\});\ }
\DoxyCodeLine{taskflow2.\mbox{\hyperlink{classtf_1_1_flow_builder_a60d7a666cab71ecfa3010b2efb0d6b57}{emplace}}([\&](\mbox{\hyperlink{classtf_1_1_runtime}{tf::Runtime}}\&\ rt)\{}
\DoxyCodeLine{\ \ \textcolor{keywordflow}{try}\ \{}
\DoxyCodeLine{\ \ \ \ rt.\mbox{\hyperlink{classtf_1_1_runtime_a1c772e90614302024cfa52fa86d75cac}{corun}}(taskflow1);}
\DoxyCodeLine{\ \ \}\ \textcolor{keywordflow}{catch}(\textcolor{keyword}{const}\ std::runtime\_error\&\ re)\ \{}
\DoxyCodeLine{\ \ \ \ std::cout\ <<\ \mbox{\hyperlink{namespacectre_a1eb09093367d4fb6ecf857afc771533a}{re}}.what()\ <<\ std::endl;}
\DoxyCodeLine{\ \ \}}
\DoxyCodeLine{\});\ }
\DoxyCodeLine{\mbox{\hyperlink{thread__pool_8cpp_a543e564a8407bbeac15cb2d929fec755}{executor}}.\mbox{\hyperlink{classtf_1_1_executor_a519777f5783981d534e9e53b99712069}{run}}(taskflow2).get();}

\end{DoxyCode}


For the above example, if the exception is not caught with \doxylink{classtf_1_1_runtime_a1c772e90614302024cfa52fa86d75cac}{tf\+::\+Runtime\+::corun}, it will be propagated to its parent task, which is the \doxylink{classtf_1_1_runtime}{tf\+::\+Runtime} object {\ttfamily rt} in this case. Then, the exception will be propagated to {\ttfamily taskflow2}.


\begin{DoxyCode}{0}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_executor}{tf::Executor}}\ \mbox{\hyperlink{thread__pool_8cpp_a543e564a8407bbeac15cb2d929fec755}{executor}};}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_taskflow}{tf::Taskflow}}\ taskflow1;}
\DoxyCodeLine{\mbox{\hyperlink{classtf_1_1_taskflow}{tf::Taskflow}}\ taskflow2;}
\DoxyCodeLine{}
\DoxyCodeLine{taskflow1.\mbox{\hyperlink{classtf_1_1_flow_builder_a60d7a666cab71ecfa3010b2efb0d6b57}{emplace}}([]()\{}
\DoxyCodeLine{\ \ \textcolor{keywordflow}{throw}\ std::runtime\_error(\textcolor{stringliteral}{"{}exception"{}});}
\DoxyCodeLine{\});\ }
\DoxyCodeLine{taskflow2.\mbox{\hyperlink{classtf_1_1_flow_builder_a60d7a666cab71ecfa3010b2efb0d6b57}{emplace}}([\&](\mbox{\hyperlink{classtf_1_1_runtime}{tf::Runtime}}\&\ rt)\{}
\DoxyCodeLine{\ \ rt.\mbox{\hyperlink{classtf_1_1_runtime_a1c772e90614302024cfa52fa86d75cac}{corun}}(taskflow1);}
\DoxyCodeLine{\});\ }
\DoxyCodeLine{}
\DoxyCodeLine{\textcolor{keywordflow}{try}\ \{}
\DoxyCodeLine{\ \ \mbox{\hyperlink{thread__pool_8cpp_a543e564a8407bbeac15cb2d929fec755}{executor}}.\mbox{\hyperlink{classtf_1_1_executor_a519777f5783981d534e9e53b99712069}{run}}(taskflow2).get();}
\DoxyCodeLine{\}}
\DoxyCodeLine{\textcolor{keywordflow}{catch}(\textcolor{keyword}{const}\ std::runtime\_error\&\ re)\ \{}
\DoxyCodeLine{\ \ std::cout\ <<\ \mbox{\hyperlink{namespacectre_a1eb09093367d4fb6ecf857afc771533a}{re}}.what()\ <<\ std::endl;}
\DoxyCodeLine{\}}

\end{DoxyCode}


For the above example, if the exception is not caught with \doxylink{classtf_1_1_runtime_a1c772e90614302024cfa52fa86d75cac}{tf\+::\+Runtime\+::corun}, it will be propagated to its parent task, which is the \doxylink{classtf_1_1_runtime}{tf\+::\+Runtime} object {\ttfamily rt} in this case. Then, the exception will be propagated to {\ttfamily taskflow2}. 